[package]
name = "kvs"
version = "0.1.0"
authors = ["Hamish MacDonald <elusivenode@gmail.com>"]
description = "A key-value store"
edition = "2018"

[dependencies]
clap = "4.3.0"

[dev-dependencies]
assert_cmd = "2.0.11"
predicates = "3.0.3"